#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <string.h>

#define SHM_SIZE 1024

int main() {
    int shmid;
    key_t key;
    char *shm, *input;
    pid_t pid;
    int status;

    // Create shared memory segment
    key = ftok(".", 'R');
    shmid = shmget(key, SHM_SIZE, IPC_CREAT | 0666);
    if (shmid < 0) {
        perror("shmget");
        exit(1);
    }

    // Attach shared memory segment
    shm = (char *) shmat(shmid, NULL, 0);
    if (shm == (char *) -1) {
        perror("shmat");
        exit(1);
    }

    // Prompt user for input
    printf("Enter text for spell checking: ");
    fgets(shm, SHM_SIZE, stdin);

    // Fork a child process
    pid = fork();

    if (pid < 0) {
        perror("fork");
        exit(1);
    } else if (pid == 0) {
        // Child process
        // Execute the spellchecker.sh script passing the shared memory input as argument
        execl("/bin/bash", "bash", "spellchecker.sh", shm, NULL);
        perror("execl");
        exit(1);
    } else {
        // Parent process
        wait(&status);

        // Read the misspelled words from a file generated by the bash script
        FILE *file = fopen("misspelled_words.txt", "r");
        if (file == NULL) {
            perror("fopen");
            exit(1);
        }

        // Read the misspelled words from the file
        char misspelled_words[SHM_SIZE];
        fgets(misspelled_words, SHM_SIZE, file);

        // Display original input and misspelled words
        printf("\nOriginal input:\n%s\n", shm);
        printf("\nMisspelled words:\n%s\n", misspelled_words);

        // Close the file
        fclose(file);

        // Detach and remove shared memory segment
        shmdt(shm);
        shmctl(shmid, IPC_RMID, NULL);
    }

    return 0;
}
